import { Provider } from 'react-redux';
import { Navigation } from 'react-native-navigation';

import Cart from './screens/Cart';
import Page from './screens/Page';
import Login from './screens/Login';
import Drawer from './screens/Drawer';
import Orders from './screens/Orders';
import Vendor from './screens/Vendor';
import Search from './screens/Search';
import Gallery from './screens/Gallery';
import Profile from './screens/Profile';
import Layouts from './screens/Layouts';
import CartBtn from './screens/CartBtn';
import WishList from './screens/WishList';
import Discussion from './screens/Discussion';
import Categories from './screens/Categories';
import WriteReview from './screens/WriteReview';
import OrderDetail from './screens/OrderDetail';
import ImagePicker from './screens/ImagePicker';
import VendorDetail from './screens/VendorDetail';
import CheckoutAuth from './screens/CheckoutAuth';
import Registration from './screens/Registration';
import ProductDetail from './screens/ProductDetail';
import Notification from './components/Notification';
import CheckoutPayment from './screens/CheckoutPayment';
import CheckoutComplete from './screens/CheckoutComplete';
import CheckoutShipping from './screens/CheckoutShipping';
import CheckoutDelivery from './screens/CheckoutDelivery';
import SettlementsCompleteWebView from './screens/SettlementsCompleteWebView';
import VendorManageOrders from './screens/VendorManage/Orders';
import VendorManageProducts from './screens/VendorManage/Products';
import VendorManageAddProductStep1 from './screens/VendorManage/AddProductStep1';
import VendorManageAddProductStep2 from './screens/VendorManage/AddProductStep2';
import VendorManageAddProductStep3 from './screens/VendorManage/AddProductStep3';
import VendorManageEditProduct from './screens/VendorManage/EditProduct';
import VendorManagePricingInventory from './screens/VendorManage/PricingInventory';
import VendorManageShippingProperties from './screens/VendorManage/ShippingProperties';
import VendorManageCategoriesPicker from './screens/VendorManage/CategoriesPicker';
import VendorManageOrderDetail from './screens/VendorManage/OrderDetail';

// register all screens of the app (including internal ones)
export default function registerScreens(store) {
  Navigation.registerComponent('Page', () => Page, store, Provider);
  Navigation.registerComponent('Cart', () => Cart, store, Provider);
  Navigation.registerComponent('Login', () => Login, store, Provider);
  Navigation.registerComponent('Drawer', () => Drawer, store, Provider);
  Navigation.registerComponent('Search', () => Search, store, Provider);
  Navigation.registerComponent('Orders', () => Orders, store, Provider);
  Navigation.registerComponent('Vendor', () => Vendor, store, Provider);
  Navigation.registerComponent('CartBtn', () => CartBtn, store, Provider);
  Navigation.registerComponent('Profile', () => Profile, store, Provider);
  Navigation.registerComponent('Gallery', () => Gallery, store, Provider);
  Navigation.registerComponent('Layouts', () => Layouts, store, Provider);
  Navigation.registerComponent('WishList', () => WishList, store, Provider);
  Navigation.registerComponent('Discussion', () => Discussion, store, Provider);
  Navigation.registerComponent('Categories', () => Categories, store, Provider);
  Navigation.registerComponent('WriteReview', () => WriteReview, store, Provider);
  Navigation.registerComponent('OrderDetail', () => OrderDetail, store, Provider);
  Navigation.registerComponent('VendorDetail', () => VendorDetail, store, Provider);
  Navigation.registerComponent('ImagePicker', () => ImagePicker, store, Provider);
  Navigation.registerComponent('Registration', () => Registration, store, Provider);
  Navigation.registerComponent('CheckoutAuth', () => CheckoutAuth, store, Provider);
  Navigation.registerComponent('Notification', () => Notification, store, Provider);
  Navigation.registerComponent('ProductDetail', () => ProductDetail, store, Provider);
  Navigation.registerComponent('CheckoutPayment', () => CheckoutPayment, store, Provider);
  Navigation.registerComponent('CheckoutDelivery', () => CheckoutDelivery, store, Provider);
  Navigation.registerComponent('CheckoutShipping', () => CheckoutShipping, store, Provider);
  Navigation.registerComponent('CheckoutComplete', () => CheckoutComplete, store, Provider);
  Navigation.registerComponent('SettlementsCompleteWebView', () => SettlementsCompleteWebView, store, Provider);
  Navigation.registerComponent('VendorManageOrders', () => VendorManageOrders, store, Provider);
  Navigation.registerComponent('VendorManageProducts', () => VendorManageProducts, store, Provider);
  Navigation.registerComponent('VendorManageAddProductStep1', () => VendorManageAddProductStep1, store, Provider);
  Navigation.registerComponent('VendorManageAddProductStep2', () => VendorManageAddProductStep2, store, Provider);
  Navigation.registerComponent('VendorManageAddProductStep3', () => VendorManageAddProductStep3, store, Provider);
  Navigation.registerComponent('VendorManageEditProduct', () => VendorManageEditProduct, store, Provider);
  Navigation.registerComponent('VendorManagePricingInventory', () => VendorManagePricingInventory, store, Provider);
  Navigation.registerComponent('VendorManageShippingProperties', () => VendorManageShippingProperties, store, Provider);
  Navigation.registerComponent('VendorManageCategoriesPicker', () => VendorManageCategoriesPicker, store, Provider);
  Navigation.registerComponent('VendorManageOrderDetail', () => VendorManageOrderDetail, store, Provider);
}
